### ISSUE TITLE
Missing ':' in ':ref:'

### ISSUE THREAD

**Issue by airnandez** [lsst/pipelines_lsst_io#66]
There is a colon missing in [this file](https://github.com/lsst/pipelines_lsst_io/blob/master/install/demo.rst) so the note in https://pipelines.lsst.io/install/demo.html#download-the-demo-project does not render correctly.

**Comment by jdswinbank** [comment]
Thanks — well spotted! [DM-12726](https://jira.lsstcorp.org/browse/DM-12726).

**Comment by jdswinbank** [comment]
Fixed in #67. Thanks again for the report!
