### ISSUE TITLE
eups added to the list of prerequisites

### ISSUE THREAD

**Issue by wadawson** [lsst/pipelines_lsst_io#70]
In hindsight it is obvious given the title of the [page](https://pipelines.lsst.io/install/newinstall.html), but I believe eups should be listed as one of the prerequisites, along with some helpful words on installing it like there are for the other preqs.

**Comment by wadawson** [comment]
Ah, I now see that it is downloaded as part of the `newinstall.sh` script. However, I think there is a problem with registration of the eups executable since I get the following error when running `source loadLSST.bash`:

`ImportError: No module named 'eups.setupcmd'`

and nothing gets returned when I type `which eups`.

**Comment by jonathansick** [comment]
@wadawson Right, at the moment EUPS is part of the stack installation itself, not something that a user externally manages.

It might be best to ask about this issue on https://community.lsst.org/c/support or on Slack with the DM team and we can attempt to reproduce your issue.

**Comment by jonathansick** [comment]
I'll close this issue at the moment. Let us know if there are any remaining installation issues, though.
